### ISSUE TITLE
Feedback/Review

### ISSUE THREAD

**Issue by clementval** [MeteoSwiss-APN/HIR#2]
This is a placeholder for my feedback/review. If any changes are simple, I'll directly issue a PR. 

1) - [x]  **named element**: As a general comment, I would remove the notion of named elements as it appears now. I think this is quite confusing and it would be more straightforward to have the element with the correct name directly. The elements can then share their internal specification but it would be clear from the beginning. This is the case for example of `lhs`/`rhs`. This would remove also the ambiguity with the actual name (in fact identifier) of variables in the IR.
Another example can be found in the example. The `vararg` name for `VarDecl` is used directly as element name can imply directly the attribute `isarg=true`. 

2) - [x] **id instead of name**: Following the previous comment, I would change the `name` in `VarDecl` and other element representing the variable in `id` which is more representative of what the information in the IR is. 

3) - [x]  **Literal**: Wouldn't it make sense to have the differentiation between String literal and integer/real constant? How do you make the difference otherwise between a string `"1.0"` and an actual real `1.0`?

4) - [x]  **binary op**: Similar to named elements, I would directly have the operation as the name of the element and not as an attribute. `DivOp`, `MulOp`, `AddOp`, `SubOp`, `PowerOp` ... Doesn^t matter then if they are all derived from a single `BinaryOp`. This would make the IR more readable. 

5) - [x] **VarAccess**: How can we access a var with `i+1` for example. The current specification accepts `Literal` elements only. I guess it should accept a restricted set of `ExprModel`. 

6) - [x] **GridDimension**: I think this element is not well defined. It as no content model but should have something like `(Literal+)` or `(Var+)` ...

7) - [x] **Program**: The content model is referencing `Dimension`but should be `GridDimension`. Can be related with 1. 

_WORK IN PROGRESS..._

**Open PRs**: 
Removal of `Stmt` and `ExprStmt` as elements #1

**Comment by cosunae** [comment]
thanks for the feedback  @clementval , some comments from my side: 

* concerning the named elements, I guess we have two ways to reference children, by name (which is the current proposal) or by position (which is what you suggest?).  I see your point that having to specify a name sometimes makes the information redundant. I think the main use case for it was to easily group an array (of dimensions for example). So if we go to "by position" I guess we will need an Array element? 
* The literal was intended to be used only within an arithmetic expression, so do we need string? Most other places where strings are needed are things like "name" of a field, and for that we are using attributes. So do we need a string literal?
* Binary op: not sure I understand, you would remove the BinaryOp and create a bunch of other elements, one for each operation? This will considerably increase the number of elements... 
* VarAccess can not do i+1, since it can dereference only scalar (not gridded fields). Something like 
```
double a[4];  ->VarDecl
a[2] = 0.0; ->VarAccess
```
This was intentional, since for `i+1` we should use FieldDecl
* GridDimension, uhmmm we can identify by index (Literal+) or by name, so currently we have a name in the attributes ?
* Program: yes, could you update it in the PR?

**Comment by clementval** [comment]
1. I think as we discussed, a position wise deduction is often what is used in IR. We can wrap list-like node in super nodes like `ParallelDimensions (Dimension+)` et `GridDimensions (Dimension+)`

**Comment by clementval** [comment]
The root node `Program` should also have several other attributes like the `version` of the HIR. It will probably evolve over time and front-end will generate a specific version. With an attribute, the toolchain can check whether the version is supported or outdated.

**Comment by cosunae** [comment]
I agree with 1, 3 and the Program element, but I didnt understand your comment on 2 & 5 (we can discuss it)
And for 4, I dont see what else we might need.

**Comment by clementval** [comment]
@cosunae I think we should move forward with the changes we agreed after discussion. I can make them and make a PR for review... Would that be fine with you?

**Comment by cosunae** [comment]
that would be great @clementval 

thanks for pushing this

**Comment by clementval** [comment]
Done with #7
